CREATE TABLE animal (
  id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   species VARCHAR(255) NOT NULL,
   provisional_name VARCHAR(255) NOT NULL,
   estimated_age INT NOT NULL,
   breed VARCHAR(255) NOT NULL,
   entry_date date NOT NULL,
   adoption_date date,
   entry_conditions VARCHAR(255) NOT NULL,
   receptor_name VARCHAR(255) NOT NULL,
   death_date date,
   animal_size VARCHAR(255) NOT NULL,
   CONSTRAINT pk_animal PRIMARY KEY (id)
);